config/routes.rb
FoodieFighters::Application.routes.draw do

  resources :foods do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  get "/home" => "page#home"
  get "/clients" => "page#clients"
  get "/battles" => "page#battles"
  get "/store" => "page#store"
  root 'page#home'
  
  devise_for :users
  mount ApiDocs::Engine => '/api-docs'

end

app/models/food.rb
class Food < ActiveRecord::Base
  paginates_per 25
  
  def Food.display_page( page )
    order(:display_name).page( page )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.display_page( params[:page] )
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food_code, :display_name, :portion_default, :portion_amount, :portion_display_name, :factor, :increment, :multiplier, :grains, :whole_grains, :vegetables, :orange_vegetables, :drkgreen_vegetables, :starchy_vegetables, :other_vegetables, :fruits, :milk, :meats, :soy, :drybeans_peas, :oils, :solid_fats, :added_sugars, :alcohol, :calories, :saturated_fats)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def clients
  end

  def battles
  end

  def store
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_code %><br>
    <%= f.text_field :food_code %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :portion_default %><br>
    <%= f.text_field :portion_default %>
  </div>
  <div class="field">
    <%= f.label :portion_amount %><br>
    <%= f.text_field :portion_amount %>
  </div>
  <div class="field">
    <%= f.label :portion_display_name %><br>
    <%= f.text_field :portion_display_name %>
  </div>
  <div class="field">
    <%= f.label :factor %><br>
    <%= f.text_field :factor %>
  </div>
  <div class="field">
    <%= f.label :portion_increment %><br>
    <%= f.text_field :portion_increment %>
  </div>
  <div class="field">
    <%= f.label :multiplier %><br>
    <%= f.text_field :multiplier %>
  </div>
  <div class="field">
    <%= f.label :grains %><br>
    <%= f.text_field :grains %>
  </div>
  <div class="field">
    <%= f.label :whole_grains %><br>
    <%= f.text_field :whole_grains %>
  </div>
  <div class="field">
    <%= f.label :vegetables %><br>
    <%= f.text_field :vegetables %>
  </div>
  <div class="field">
    <%= f.label :orange_vegetables %><br>
    <%= f.text_field :orange_vegetables %>
  </div>
  <div class="field">
    <%= f.label :drkgreen_vegetables %><br>
    <%= f.text_field :drkgreen_vegetables %>
  </div>
  <div class="field">
    <%= f.label :starchy_vegetables %><br>
    <%= f.text_field :starchy_vegetables %>
  </div>
  <div class="field">
    <%= f.label :other_vegetables %><br>
    <%= f.text_field :other_vegetables %>
  </div>
  <div class="field">
    <%= f.label :fruits %><br>
    <%= f.text_field :fruits %>
  </div>
  <div class="field">
    <%= f.label :milk %><br>
    <%= f.text_field :milk %>
  </div>
  <div class="field">
    <%= f.label :meats %><br>
    <%= f.text_field :meats %>
  </div>
  <div class="field">
    <%= f.label :soy %><br>
    <%= f.text_field :soy %>
  </div>
  <div class="field">
    <%= f.label :drybeans_peas %><br>
    <%= f.text_field :drybeans_peas %>
  </div>
  <div class="field">
    <%= f.label :oils %><br>
    <%= f.text_field :oils %>
  </div>
  <div class="field">
    <%= f.label :solid_fats %><br>
    <%= f.text_field :solid_fats %>
  </div>
  <div class="field">
    <%= f.label :added_sugars %><br>
    <%= f.text_field :added_sugars %>
  </div>
  <div class="field">
    <%= f.label :alcohol %><br>
    <%= f.text_field :alcohol %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :saturated_fats %><br>
    <%= f.text_field :saturated_fats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>
<%= paginate @foods %>
<table>
  <thead>
    <tr>
      <th>Food code</th>
      <th>Display name</th>
      <th>Portion default</th>
      <th>Portion amount</th>
      <th>Portion display name</th>
      <th>Factor</th>
      <th>Portion Increment</th>
      <th>Multiplier</th>
      <th>Grains</th>
      <th>Whole grains</th>
      <th>Vegetables</th>
      <th>Orange vegetables</th>
      <th>Drkgreen vegetables</th>
      <th>Starchy vegetables</th>
      <th>Other vegetables</th>
      <th>Fruits</th>
      <th>Milk</th>
      <th>Meats</th>
      <th>Soy</th>
      <th>Drybeans peas</th>
      <th>Oils</th>
      <th>Solid fats</th>
      <th>Added sugars</th>
      <th>Alcohol</th>
      <th>Calories</th>
      <th>Saturated fats</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.food_code %></td>
        <td><%= food.display_name %></td>
        <td><%= food.portion_default %></td>
        <td><%= food.portion_amount %></td>
        <td><%= food.portion_display_name %></td>
        <td><%= food.factor %></td>
        <td><%= food.portion_increment %></td>
        <td><%= food.multiplier %></td>
        <td><%= food.grains %></td>
        <td><%= food.whole_grains %></td>
        <td><%= food.vegetables %></td>
        <td><%= food.orange_vegetables %></td>
        <td><%= food.drkgreen_vegetables %></td>
        <td><%= food.starchy_vegetables %></td>
        <td><%= food.other_vegetables %></td>
        <td><%= food.fruits %></td>
        <td><%= food.milk %></td>
        <td><%= food.meats %></td>
        <td><%= food.soy %></td>
        <td><%= food.drybeans_peas %></td>
        <td><%= food.oils %></td>
        <td><%= food.solid_fats %></td>
        <td><%= food.added_sugars %></td>
        <td><%= food.alcohol %></td>
        <td><%= food.calories %></td>
        <td><%= food.saturated_fats %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @foods %>
<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food code:</strong>
  <%= @food.food_code %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @food.display_name %>
</p>

<p>
  <strong>Portion default:</strong>
  <%= @food.portion_default %>
</p>

<p>
  <strong>Portion amount:</strong>
  <%= @food.portion_amount %>
</p>

<p>
  <strong>Portion display name:</strong>
  <%= @food.portion_display_name %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @food.factor %>
</p>

<p>
  <strong>Portion Increment:</strong>
  <%= @food.portion_increment %>
</p>

<p>
  <strong>Multiplier:</strong>
  <%= @food.multiplier %>
</p>

<p>
  <strong>Grains:</strong>
  <%= @food.grains %>
</p>

<p>
  <strong>Whole grains:</strong>
  <%= @food.whole_grains %>
</p>

<p>
  <strong>Vegetables:</strong>
  <%= @food.vegetables %>
</p>

<p>
  <strong>Orange vegetables:</strong>
  <%= @food.orange_vegetables %>
</p>

<p>
  <strong>Drkgreen vegetables:</strong>
  <%= @food.drkgreen_vegetables %>
</p>

<p>
  <strong>Starchy vegetables:</strong>
  <%= @food.starchy_vegetables %>
</p>

<p>
  <strong>Other vegetables:</strong>
  <%= @food.other_vegetables %>
</p>

<p>
  <strong>Fruits:</strong>
  <%= @food.fruits %>
</p>

<p>
  <strong>Milk:</strong>
  <%= @food.milk %>
</p>

<p>
  <strong>Meats:</strong>
  <%= @food.meats %>
</p>

<p>
  <strong>Soy:</strong>
  <%= @food.soy %>
</p>

<p>
  <strong>Drybeans peas:</strong>
  <%= @food.drybeans_peas %>
</p>

<p>
  <strong>Oils:</strong>
  <%= @food.oils %>
</p>

<p>
  <strong>Solid fats:</strong>
  <%= @food.solid_fats %>
</p>

<p>
  <strong>Added sugars:</strong>
  <%= @food.added_sugars %>
</p>

<p>
  <strong>Alcohol:</strong>
  <%= @food.alcohol %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @food.calories %>
</p>

<p>
  <strong>Saturated fats:</strong>
  <%= @food.saturated_fats %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodieFighters</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/page/battles.html.erb
<h1>Page#battles</h1>
<p>Find me in app/views/page/battles.html.erb</p>

app/views/page/clients.html.erb
<h1>Page#clients</h1>
<p>Find me in app/views/page/clients.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/store.html.erb
<h1>Page#store</h1>
<p>Find me in app/views/page/store.html.erb</p>